language: cpp
compiler:
  - gcc
before_script:
  - mkdir kf5-release && cd kf5-release
  - wget https://github.com/chigraph/precompiled-kf5-linux/releases/download/precompiled/kf5-gcc6-linux64-release.tar.xz -O kf5.tar.xz
  - tar xf kf5.tar.xz
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
